### ISSUE TITLE
H&M Game progress is not saved in Sahrani terrain (CUP Terrains - Maps)

### ISSUE THREAD

**Issue by Marcos102** [Vdauphin/HeartsAndMinds#1120]
Arma 3 Version: 2.04 stable
CBA Version: 3.15.3.210310 stable
ACE3 Version: 3.13.6 stable
Hearts and minds Version: 1.21.3 stable

Mods:

- CBA_A3
- ace
-CUP Weapons
-CUP Units
-CUP Vehicles
-CUP Terrains - Core
-CUP Terrains - Maps
-task force radio

Description:
Nothing happens when the server administrator tries to save the progress in the database (Using his own interaction key)
Also, no message is displayed and no progress can be "loaded". No error or crash messages are even displayed.

Steps to reproduce:
- Launch the H&M mission on a dedicated server using the Sahrani terrain .
- Log as an administrator
- Try to save the game

**Comment by Vdauphin** [comment]
Hello,

Please fill up the issue template correctly

If it doesn't work it is because:
- You didn't save -> Login as admin, self-interaction, database, save, wait and done.
- You fuck up the mission file, download it again from the release page
- The Arma server exe don't have write acces to the file: Vdauphin.vars.Arma3Profile see https://community.bistudio.com/wiki/profileNamespace and https://community.bistudio.com/wiki/Profile

Cheers
