### ISSUE TITLE
CommandPassword Out In The Open

### ISSUE THREAD

**Issue by NoAce4U** [Vdauphin/HeartsAndMinds#1156]
When combing through the mission files I've noticed a possible issue with the Command Password being openly available for users who join to see if the crack open the mission

`btc_db_serverCommandPassword = "btc_password"; //Define the same password in server.cfg like this: serverCommandPassword = "btc_password";`

See here for possible fix

`btc_db_serverCommandPassword = call compile preprocessFileLineNumbers "\password.hpp";`

Then define the password in the hpp as 

`"thepassword"`

Obviously placing the hpp into a folder on the server and no longer in the mission.pbo

**Comment by Vdauphin** [comment]
Hello,

Yes, it is better to hide it inside a file outside mission folder
Honestly, I choosed this solution to make it simple for admins. So, I don't have to write a wiki page to explain it

But, if an admin consider security a priority, he must already run server with Battle Eyes and keys verification. So base on this assumption, players knowing the `serverCommandPassword` can't really run any server command. Because the player need an allowed mod to execute server command.

Cheers
