### ISSUE TITLE
`addTicket` is not working with side wide tickets

### ISSUE THREAD

**Issue by Zakant** [Vdauphin/HeartsAndMinds#1462]
**Hearts and minds Version:** `1.x.x` (stable / dev + commit hash)

**Description:**
- Adding tickets using `btc_respawn_fnc_addTicket` is not working properly when side shared tickets are enabled.
- The "bis respawn" tickets are adjusted fine, but the internal hashmap `btc_respawn_tickets` is not.

**Steps to reproduce:**
- Enable shared tickets
- Let a player die
- Recover the body bag
- See that the respawn count within the hasmap (which is essential for saving and loading) is not matching the "bis respawn" ticket count

**Comment by Vdauphin** [comment]
Hello,

Because hashmap is only update just before saving with tickets share between side 
https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/db/save.sqf#L220

You can notice it here: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/respawn/addTicket.sqf#L46

There is no reason to update it because tickets from side are monitor by `BIS_fnc_respawnTickets`. 
Which is not the case for player tickets because if player disconnect, there is no way to recover tickets with `BIS_fnc_respawnTickets` 

Cheers

**Comment by Vdauphin** [comment]
Wait, are you talking about master_daily?

**Comment by Zakant** [comment]
Yes, i'm on `master_daily`. In that branch, saving tickets apparently does not work... The corresponding line is missing here: https://github.com/Vdauphin/HeartsAndMinds/blob/master_daily/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/db/save.sqf#L220.
I only started to investigate the problem when the ticket count after loading a game didn't matched what i expected...
