### ISSUE TITLE
Question: ACE modules / hearing (the ringing noise)

### ISSUE THREAD

**Issue by Dexious** [Vdauphin/HeartsAndMinds#221]
Hello,

Are we able to add more or change the ACE modules in the mission or it's going to break things?

e.x Add ACE module for the hearing to disable the ringing noise.

Thanks

**Comment by Vdauphin** [comment]
Hello agian :) 
Yes you are allow to add or change ACEmodule, it should not break thnigs.

> e.x Add ACE module for the hearing to disable the ringing noise.

the earing is not due to ACE3 when you hear a ammo cache exploding or suicider, it is fire by the mission !

https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/ied/boom.sqf#L9

https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/ied/allahu_akbar.sqf#L15

https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf#L17

Remove them if you dislike :)

**Comment by Dexious** [comment]
Thanks :) :+1:

**Comment by Vdauphin** [comment]
Actual hearing deafness : 
- use playSound3d["A3\Missions_F_EPA\data\sounds\combat_deafness.wss", objNull, false, _pos_ASL, 1, 1];
- Problem : It is not compatible with ACE3 hear plug.

New command could be : 
- https://github.com/acemod/ACE3/blob/master/addons/hearing/functions/fnc_earRinging.sqf
