### ISSUE TITLE
Bug: Spawned vehicles have no engine sound.

### ISSUE THREAD

**Issue by Dexious** [Vdauphin/HeartsAndMinds#222]
Hello i noticed that the vehicles that are getting spawned either Civilian or Enemy don't have sound.
You can't hear the engine.
If you spawn them with Zeus they work fine.

We were surprised when enemies came up to us with vehicles that we didn't even hear.

How to test:
Use Zeus and find a car that got spawned.

**Comment by Vdauphin** [comment]
Not link to the hearts and minds :/

If you launch arma 3 without mod and join a dedicate server without mod. If you have the debug console execute this (before get your position and replace it is the code) : 

`_Spos= [5058.69,6448.05,0.00143909]; 
_veh = createVehicle ["C_Hatchback_01_F", _Spos, [], 0, "NONE"];
("C_man_1") createUnit [_Spos, createGroup civilian, "this moveinDriver _veh; this assignAsDriver _veh;"];`

you will have no sound from engine vehicle ...
If you do the same in a multiplayer game, you launched, the bug is not present.

Looks like it is a BI fault :/

**Comment by Dexious** [comment]
Hello could you have a look at this forum post?

https://forums.bistudio.com/topic/190727-solved-cant-turn-engine-on-after-spawning-an-empty-vehicle-maybe-a-bug/

**Comment by Vdauphin** [comment]
there are not spawn at position 0,0,0 and vehicle can drive :/

**Comment by Dexious** [comment]
Ok i'll see if i can make a bug report to BI with a link to this issue so they can use your code above. :+1:

**Comment by Vdauphin** [comment]
see : https://dev.arma3.com/post/spotrep-00061

> Fixed: Engines of AI-controlled vehicles in multiplayer were not audible (https://feedback.bistudio.com/T120341)
