### ISSUE TITLE
Question: Use of R3F Logistics for persistent objects OR Add more objects to the crate list?

### ISSUE THREAD

**Issue by Dexious** [Vdauphin/HeartsAndMinds#225]
How hard would it be to be able to use R3F Logistics script to spawn persistent objects?

I know it can be done with ALiVE mod as i have used it by following this code addition in R3F script
R3F_LOG\objet_deplacable\relacher.sqf at line 12
`[LOGIC_ALIVE,"updateObject",[R3F_LOG_joueur_deplace_objet]] call ALIVE_fnc_logistics;`

The above made so when you released an object it got saved or marked to be saved.

Forum post: https://forums.bistudio.com/topic/170033-r3f-logistics/page-7#entry2753704

OR

Could i use the mission.sqf file to add more objects or even more categories?

**Comment by Vdauphin** [comment]
Helllooo!!!

> How hard would it be to be able to use R3F Logistics script to spawn persistent objects?

I think it is a waste of time to use R3F logistic and will add confusion. (H&M have already a deep logisitc system, you can paradrop, carry, tow, lift object you are not suppose to lisft with the vanilla). 


> The above made so when you released an object it got saved or marked to be saved.

> Forum post: https://forums.bistudio.com/topic/170033-r3f-logistics/page-7#entry2753704

And you don't need alive to make it persisitant because it is ALREADY persisitant x)

> Could i use the mission.sqf file to add more objects or even more categories?

Yes add all object you need. It is not limited to anything! You can also add vehicle what ever. And it will be persistant. (It is persistant if you save before restart ...)

**Comment by Dexious** [comment]
Yea i know it's persistent. I just referenced ALiVE to show you that i only need to place a piece of code where the item from R3F is getting created.

The code that adds that object to your saving object list.

I'll see if i can use your "mission.sqf" file to add more categories/objects there.

**Comment by Vdauphin** [comment]
The line for H&M is here : 
https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/log/create_s.sqf#L17

**Comment by Dexious** [comment]
Thank you very much Vdauphin :) :+1:

**Comment by Vdauphin** [comment]
You welcome :)
