### ISSUE TITLE
Bug: Is there really a bonus for disarming an IED?

### ISSUE THREAD

**Issue by Doctor-Butts** [Vdauphin/HeartsAndMinds#326]
When trying to figure out whether the mission considers the actual disarm action disarming, or simply shooting the IED to add to the rep bonus, I could not find a call to change the rep for btc_rep_bonus_disarm

All other rep options in mission.sqf refer to some event in other scripts where it will be (rep) spawn btc_fnc_rep_change, but there is nothing for disarming IED's that I could find.

**Comment by Vdauphin** [comment]
This is a bug due to this : https://github.com/Vdauphin/HeartsAndMinds/pull/214

I forget to add the addeventhandler link to that action. Should looks like:
`["ace ied event", { [btc_rep_bonus_disarm,"btc_fnc_rep_change",false] spawn BIS_fnc_MP;}] call CBA_fnc_addEventHandler;`

Thanks for this clear report.

**Comment by Doctor-Butts** [comment]
Thanks for the quick reply, but I'm not sure where that code would go.

**Comment by Vdauphin** [comment]
This is just a note for me ^^
