### ISSUE TITLE
Support for EODS IEDs

### ISSUE THREAD

**Issue by WSIContractor** [Vdauphin/HeartsAndMinds#336]
Is is possible to get support as a parameter for the type of IEDs use, where you can use the vanilla, mine detector, and or defuse kit from ACE3 and then finally using the EODS mod.

When EODS is selected then the appropriate mines are set and that the EODS mine detector can be used and any other items from the EODS suite mod.

Thanks again.

**Comment by Vdauphin** [comment]
> where you can use the vanilla

IEDs Vanilla are obsolete since the H&M can only be run with ACE3 (https://github.com/Vdauphin/HeartsAndMinds/wiki/5:-Mods-dependency). 

> When EODS is selected then the appropriate mines are set 

I don't know at all about EODS. I am surprise the EODS suite mod is not already working with the IED spawn by the H&M. Since this https://github.com/Vdauphin/HeartsAndMinds/pull/214 , H&M use vanilla IED: https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/mission.sqf#L219
You should be allow to use the EODS suite without any problem.

If you want to have more IEDs type, you just have to add IEDs type inside the array `btc_type_ieds_ace`

Best regards

**Comment by WSIContractor** [comment]
Thanks, going to look into it more and see by adding the EODS ied class names to the L219 in the mission.sqf file.

**Comment by Vdauphin** [comment]
Hello, do you have any feedback on this ? Best regards

**Comment by WSIContractor** [comment]
To tell you the truth. I have not had a chance to look at it. I was going to check it out this weekend. I will let you know then. Thanks.

**Comment by Vdauphin** [comment]
Finally, did you try it ?

**Comment by Vdauphin** [comment]
https://github.com/Vdauphin/HeartsAndMinds/discussions/1164
