### ISSUE TITLE
How to spawn with custom loadout

### ISSUE THREAD

**Issue by formtapez** [Vdauphin/HeartsAndMinds#379]
I'm trying to figure out how to edit a mission so every player has his very own customized loadout. When i edit the loadout using Eden Editor, at spawn the scripts will delete all weapons and backpack content, etc.
How can i prevent this?

While i was searching for the code which causes this, i found "**btc_gear_dlg**" at several places.
What is this? Is there a hidden "Gear Dialog" (Menu) which i didn't found yet?
How can i open this?

**Comment by Vdauphin** [comment]
Hello,

> How can i prevent this?

Just remove this line :  `removeAllWeapons player;`
 https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/init_player.sqf#L24

> What is this? Is there a hidden "Gear Dialog" (Menu) which i didn't found yet?

I have no idea what this is. Looks like this code was used before the H&M has BIS Arsenal, not sure :/ . Those function are not compile by the mission actually. @Giallustio removed them may be because there are no more usefull. This could be investigate throught the vanilla backup file :[=BTC=co@22_Hearts_and_Minds.Altis[BACKUP].7z](https://github.com/Vdauphin/HeartsAndMinds/blob/master_stable/%3DBTC%3Dco%4022_Hearts_and_Minds.Altis%5BBACKUP%5D.7z). 

See you!

**Comment by formtapez** [comment]
Cool, that works.
Thank you!
