### ISSUE TITLE
vehicle despawner

### ISSUE THREAD

**Issue by eststar** [Vdauphin/HeartsAndMinds#552]
I don't know here is right place to suggest, I think vehicle despawner is needed to pair with vehicle spawner. I am using vehicle spawner frequently, but only way I can remove those spawned vehicles is zeus. Can you make despawner for not using zeus?

**Comment by Vdauphin** [comment]
Hello,
> I don't know here is right place to suggest,

It is :)

> but only way I can remove those spawned vehicles is zeus.

It is the correct way to do it, no worries about this.

> Can you make despawner for not using zeus?

Since you need to be admin to use vehicle spawner, you also have the zeus interface to remove them.
I was think about removing the vehicle spawner and only use the Zeus to add vehicle (and remove as you already do).

What is the issue by using the Zeus to despawn vehicles ?

**Comment by eststar** [comment]
I changed that somehow to make everyone can. Because not everyone have admin access to spawn vehicle. So it might be unable to do mission like if base is an island and there is no vehicle left in base. 
And also if access zeus zeus can see the enemy movement or the hideout, ammo cache even not intended to do that. So to prevent that I think it is good to make despawner.
Ah and one more issue about this, that spawned vehicle remain as wreck after destroyed. And if even zeus delete that vehicle, the wreck marker remains.

**Comment by Vdauphin** [comment]
Hello,

> So it might be unable to do mission like if base is an island and there is no vehicle left in base.

Just use a FOB you previously deployed near vehicles you moved on the main island.

> Ah and one more issue about this, that spawned vehicle remain as wreck after destroyed.

It is intended, just use the repair wreck feature at logistic point (https://github.com/Vdauphin/HeartsAndMinds/wiki/InGame-documentation#logistic-point).

> And if even zeus delete that vehicle, the wreck marker remains.

I agree this should be improved.

The spawner is here to give the possibility for admin to add new vehicle when the H&M is loaded with the data base because he can't add them through mission.sqm (until the data base is reset). 

Cheers
