### ISSUE TITLE
throw leaflets with drone

### ISSUE THREAD

**Issue by defender82** [Vdauphin/HeartsAndMinds#595]
**Description:**
- in core/fnc/civ/add_leaflets.sqf  is a classname that I could not find in the editor "UAV_06_base_F".
I think that's why the problem comes that you can´t throw off any leaflets with the drone in the game.

With "B_UAV_06_F" , the drone is loaded with leaflets, but you can not throw them off.
With "B_UAV_01_F", everything works fine.

**Steps to reproduce:**
- go in Editor, try to throw leaflets with an NATO AL6 drone
- Add screenshots by drag and drop it here.

**Comment by Vdauphin** [comment]
Hello,

> I think that's why the problem comes that you can´t throw off any leaflets with the drone in the game.

No because `"UAV_06_base_F"` is the parent of `"B_UAV_06_F"` as you can see:

![20180829192150_1](https://user-images.githubusercontent.com/14364400/44804210-007c8b00-abc1-11e8-9501-9857cfac9daa.jpg)


Also this screenshot show you that all leaflets is correctly loaded (`[["1Rnd_Leaflets_West_F",1,true,65536,"Bomb_Leaflets"]]`) so you should be allow to drop leaflets.

Can you check same stuff and send it here ?

I am just using the BI system https://community.bistudio.com/wiki/Arma_3_Leaflets#Mission_Usage system.
For refrence : https://forums.bohemia.net/forums/topic/165948-mp-btc-hearts-and-minds/?page=41&tab=comments#comment-3296386 .

Cheers
