### ISSUE TITLE
[Question] How to tweak enemy amount of cities?

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#636]
I'd like to know how to tweak enemy amount of cities.

I've tried to add more enemies to my mission (about 50 enemies each city).

I read core/def/mission.sqf file, but found no related tweakable contents,

However, I found these codes in core/fnc/city/activate.sqf:
https://github.com/Vdauphin/HeartsAndMinds/blob/c7c46da54c9b63646f941040355f9a82187620ee/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L105-L115

I changed these value to:

```
    // Edited - Maximum number of enemy group
    private _max_number_group = (switch _type do {
        case "Hill" : {8};
        case "NameLocal" : {12};
        case "NameVillage" : {15};
        case "NameCity" : {18};
        case "NameCityCapital" : {25};
        case "Airport" : {25};
        case "NameMarine" : {6};
        default {10};
    });
```

Enemy units increased to about 25 each city, but still not enough for me.

Then I changed these value to:

```
// Edited - Maximum number of enemy group
    private _max_number_group = (switch _type do {
        case "Hill" : {10};
        case "NameLocal" : {15};
        case "NameVillage" : {20};
        case "NameCity" : {25};
        case "NameCityCapital" : {30};
        case "Airport" : {30};
        case "NameMarine" : {8};
        default {15};
    });
```

However, I noticed the total numbers of units in each city decreased to 14-16.

So I'm here to ask for your help, thanks for your reply.

**Comment by Vdauphin** [comment]
Hello,

https://github.com/Vdauphin/HeartsAndMinds/blob/c7c46da54c9b63646f941040355f9a82187620ee/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L105-L115

This is just the Maximum number of enemy group. This isn't directly related to the number of enemies. This tweak the number of group depends on city type.

https://github.com/Vdauphin/HeartsAndMinds/blob/c7c46da54c9b63646f941040355f9a82187620ee/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L118

`_p_mil_group_ratio * (1 + random _max_number_group))` show you that you have a random probability to have between 1 to `_max_number_group` number of group inside the town. You can increase the number of group by increasing the [enemy density parameter](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L74-L79) but it is still fully random and unpredictable. You could replace the randomization the number of to the exact number you want.

Then the number of enemy inside each group ([btc_fnc_mil_create_group](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf)) is define if there are inside a building or in patrol around the city. This is also random due to: `random 1`. If it is a patrol, then the number inside the group is randomize by : `1 + round random [0, 1, 2]`. You could change this randomization to the desired value.

Honestly, increasing the number of enemies isn't really a good idea. I would prefer increase the number of hideout to 10 or more or activate parameter Add armed vehicles in Hideout:, Add armed vehicles in Side mission/Cache: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L92-L103 and Enemy uses Tank: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L50-L55

Good luck

**Comment by GoldJohnKing** [comment]
Yep, I got it.

Two more questions:

1. Will enemy density parameters exceed 100 be valid and take effects? Will it cause potential bugs?
2. There seems to be random amount of cities without enemy, I'd like to lower that rate, how?

**Comment by Vdauphin** [comment]
Hello,
>     1. I noticed side missions stop to auto generate after last one is done because total amout of AI exceeds limit.

There is no limit.

>         1. Then I set maximum number of military patrol parameters (btc_p_patrol_max) to 100 (default 10), but seems not taking effets. So the question is how to increase the maximum limit?

With this prameters you have 100 patrols spawning which is not a really good idea (it will spawn around you between 500 to 1000 IA) ... Your server will crash for sure. 


>     2\. There seems to be random amount of cities without enemy, I'd like to lower that rate, how?

https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/init.sqf#L65 
`random 1 > 0.45` if you decrease the `0.45` you will have more city with enemies.

Cheers

**Comment by GoldJohnKing** [comment]
I‘m pretty sure that when a city activates, there are two types of enemies spawned:
1. Enemies spawned inside the city, amount was controled by "btc_p_mil_group_ratio" parameter.
2. Patrols spawned in nearby cities, amount was controled by "btc_p_patrol_max" parameter.
When people leave it, the first kind will despawn for sure, but the second type will not be despawned. Sometimes the second type of enemies will not continue spawning if none of them are killed (might be up to limit?), but in some cases they will spawn every time when player enter a new city, causing huge amount of AI in the mission.

Thanks a lot for your help!

**Comment by Vdauphin** [comment]
Hello,
>     1. Enemies spawned inside the city, amount was controled by "btc_p_mil_group_ratio" parameter.

Yes

>     2\. Patrols spawned in nearby cities, amount was controled by "btc_p_patrol_max" parameter.     2\. When people leave it, the first kind will despawn for sure, but the second type will not be despawned.

Yes

>     2\. Sometimes the second type of enemies will not continue spawning if none of them are killed (might be up to limit?)

The limit is random and calculated each time a player enter inside a city: https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L219
But can't be upper than "btc_p_patrol_max" (https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L216).

Cheers
