### ISSUE TITLE
hideouts

### ISSUE THREAD

**Issue by topden** [Vdauphin/HeartsAndMinds#643]
http://joxi.ru/zAN6z1WTBQwv7A

Could you change the hideouts , because they sometimes appear in places where objects do not stand exactly or fail. And some coordinates http://joxi.ru/MAjBEkqC4nYjbA  becouse not interested see hideout near road or water or in the city) http://joxi.ru/v29G3wph3VjZ8r
Or help me find file with coordinates. PLS)

**Comment by Vdauphin** [comment]
Hello,

> because they sometimes appear in places where objects do not stand exactly or fail. And some coordinates http://joxi.ru/MAjBEkqC4nYjbA becouse not interested see hideout near road or water or in the city) http://joxi.ru/v29G3wph3VjZ8r

This is by design, H&M use city position to find a safe area for the hideouts

> help me find file with coordinates. PLS)

Hideouts are generated randomly by this function : https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf#L48 So at each new game a new position will be define and add a lot of replay ability

If you go deeper you can see H&M try multiple time to find a safe position which isn't easy particular on Tanoa where there is trees every where. If you try to remove position close to water or road you will find nearly no correct position and they will spawn in the sky

See you soon

**Comment by topden** [comment]
OK. THX
