### ISSUE TITLE
City with ridiculous radius are not deactivated correctly

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#751]
**Arma 3 Version:** `1.94` (stable)
**CBA Version:** `3.12.0` (stable)
**ACE3 Version:** `3.12.6` (stable)
**RHS USAF Version:** `0.4.9` (stable)
**Hearts and minds Version:** `1.19.7` (stable)

**Mods:**
```
- CBA_A3
- ace
- RHS USAF
- RHS AFRF
```

**Description:**
- Enemy infantry spawned in non-side-mission cities wont despawn if player leave the city, it's pretty resource consuming if player drive all the way to reach a far distance side-mission, and some of them even can not be deleted by Zeus.
- This happens the first time I use H&M, and it seems to happen no matter what faction I choose. It affect both EAST and GUER as far as I tested, though I mainly use RHS AFRF Russian VDV. The undeletable units' classes are just random, too.
- Though this happens mostly on patrols between cities (waypoints to another city, marked by "p-1", "p-2", ... in debug mode), it happens to defenders of a city (cycle waypoints within a city), too.
- It seems not related to hideouts, because it also happens in cities without hideout or cities far from a hideout, and they do not have waypoints to a hideout.
- Besides, some of the AI in a side-mission area wont despawn when mission finished and player leave the area.
- I'm not sure if it's a bug or designed feature. If it's a feature, would it be possible to despawn patrol AIs moving towards a non-player city if those AIs are far away from other players? Or would it be possible to reset their waypoints to side-mission areas or attack players' base? Having groups of non-useful AI is truly annoying.
- I'm not sure if I make it clear...

**Steps to reproduce:**
- Start the mission.
- Drive all way long from cities to cities.
- Login Zeus interface, then you'll see amounts of AIs left on the whole terrain.
- Use ACE or Achilles to update editable objects, then try to delete a group of AI.
- You'll probably find that most AI in the group are deleted, but there's somtimes some AI left, which cannot be deleted.

**Additional:**
My mission parameters (param.hpp) here 
https://pastebin.com/k2anyJCG
(Github Gists has been blocked in China, so I could only provide pastebin link.)

**Screenshots:**
Here's a triggered city but players far from it now, side-mission finished(failed), and hideout destroyed, please notice left AIs and their waypoints:
![107410_20190813163911_1](https://user-images.githubusercontent.com/26923626/62927524-48ec8300-bde9-11e9-9099-f0a448cd0624.png)

Here are AIs spawned by triggered non-side-mission city but players already leave the area, please notice that AIs' waypoints aim a non-side-mission and non-hideout city:
![107410_20190813164243_1](https://user-images.githubusercontent.com/26923626/62927657-8f41e200-bde9-11e9-93b8-5a4b65f2b70a.png)

This is the first city activated by players, please notice that the patrol groups have no waypoints to the side-mission city:
![107410_20190813180505_1](https://user-images.githubusercontent.com/26923626/62933608-2d877500-bdf5-11e9-9baf-3a41b5354459.png)

**Comment by Vdauphin** [comment]
> Enemy infantry spawned in non-side-mission cities wont despawn if player leave the city,

I am a bit surprise as it works pretty well if the city radius properties from the map is correct. The H&M takes it as reference to search and delete those group ([de_activate.sqf#L58](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf#L58)). I can see you are using lythium. If I remember well, those radius has been badly configured from the mod Author. I will check that

> and some of them even can not be deleted by Zeus.

H&M doesn't change that behavior, sound more like a bug from Zeus or mod you are using

> This happens the first time I use H&M, and it seems to happen no matter what faction I choose. It affect both EAST and GUER as far as I tested,

Do you mean the Side (EAST and GUER) but with the same faction ie : RHS AFRF Russian VDV? I think it is just a bug from RHS

> Though this happens mostly on patrols between cities (waypoints to another city, marked by "p-1", "p-2", ... in debug mode), it happens to defenders of a city (cycle waypoints within a city), too.

Those are just military patrol, you have classic patrol, some patrol leaving hideout and try to take control of clean city or sometimes when you do bad thing civilian call them. Their behavior looks close to this : 
- they spwan when player is around
- they traval to their destination
- when they are at the destination they patrol around
- if no player around, they are removed
- if not they go to an other city

So they never disappear by magic but classic patrol/patrol leaving hideout doesn't spawn infinitely. One have a parameter  btc_p_patrol_max and the second a counter time between spawn.
This should not affect server performance as the number of patrol is low. 

> Besides, some of the AI in a side-mission area wont despawn when mission finished and player leave the area.

Yes, some side missing call militia and those despawn when until all waypoints are completed and if player is not around.

> would it be possible to despawn patrol AIs moving towards a non-player city if those AIs are far away from other players? 

Honestly, it is part of the game play. When you enter in a city enemy start moving around you if you leave it relly fast them you could face those guys. Also all patrol are allways clean up at the end. 

> Or would it be possible to reset their waypoints to side-mission areas or attack players' base? 

It could be possible but doesn't make a lot of sence. Those patrol are suppose to not make your life easy when you are patrolling around the map. If they just go to your base and destroy everything you will get really in trouble

> Having groups of non-useful AI is truly annoying.

Those are non-useful until you met them or get their location by talking to civilian. Those patrol don't know your position, if they just rush you, you will be annoyed trust me. Also a high number of patrol around a location will help you to identify hideout location and make the mission more immersive as helicopter pilot.
It is really hard to spawn a patrol somewhere and be sure players will met them because you can't predict the AI and player path. The only way to do it would be to spawn AI 300 meters in front of player but this will kill the immersion when you start to use goggles, vehicle with zoom in turret, drone or helicopter
Spawning patrol around player and hoping player find them (thanks to civilian, drone, helicopter or just randomly) is the best compromise simply because it is what is happening in real life

> Here's a triggered city but players far from it now, side-mission finished(failed), and hideout destroyed, please notice left AIs and their waypoints:

Looks really like the Lythuim map doesn't have correct city radius, I will look

> Here are AIs spawned by triggered non-side-mission city but players already leave the area, please notice that AIs' waypoints aim a non-side-mission and non-hideout city:

Yes it is an intended feature. Patrol select the next city after the player like this:
spawning partrol city --> player position --> opposit city
So the patrol will drive to the player city and then continue to an other city. So if player stay somewhere the patrol will met him and if player ontinu, the patrol will met the player if they go in the opposit direction

I hope this will help you to understand how H&M handle patrol. It is not perfect but I hope you understand the complexity of the problem.

**Comment by GoldJohnKing** [comment]
Thanks a lot for your answer truly described partol behaviors in details and helped me understand the purpose to design it and how it works.

> H&M doesn't change that behavior, sound more like a bug from Zeus or mod you are using

I'm not sure if it's H&M's problem, but I have never notice similar problem happens on other mutiplayer missions I have used, such as KP Liberation and Invade & Annex, although all my servers always use the same mods. This also happens on multiple terrains (I'll mention them below), so I bet it's not a terrain based problem.

> Do you mean the Side (EAST and GUER) but with the same faction ie : RHS AFRF Russian VDV? I think it is just a bug from RHS

No. I means no matter what faction or what side I choose as enemy faction, this always happen.

> Looks really like the Lythuim map doesn't have correct city radius, I will look

I dont remember if this happens on Altis, for I haven't been using Altis for a really long time. But besides Lythium (based on Jbad), this also happens on some CUP based map, such as Lingor and Duala. This could be a clue.

**Comment by Vdauphin** [comment]
So it is a map config issue. Go in multiplayer and select debug and set 0 meter for spawn city radius offset. You will see what value the map author set to each city. Here is an example (I took your branch MPRI-Lythium):
![20190814000843_1](https://user-images.githubusercontent.com/14364400/62980999-668d0d00-be28-11e9-93d7-689e8051b11b.jpg)

First, a lot of them are ridiculously small and completely irrelevant accordingly to the type of city.
The old castle has a city radius correct but for example IbanCampbase or Shegara are even not visible, but all of them are NameVillage and have house all around which doesn't make any sense. At least they should be just Hill accordingly to the configured city radius.

This is really important for H&M because if this radius is ridiculously small, units will not found suitable position to spawn (H&M need to avoid rock and house so AI are not stuck like retard). So they will spawn outside of the circle and when you left the city H&M will only remove those units inside of the circle.

Increasing the spawn city radius offset parameter will not help you because it is just increasing how far the city will be activated by player but not increase the city AI spawn radius. 

Here is a really good example of city radius properly configured. The circle is twice bigger than the city
![20190814001155_1](https://user-images.githubusercontent.com/14364400/62981001-6987fd80-be28-11e9-8221-4186ad4b0403.jpg)

When I tested your branch, I notice that some crazy AI number inside patrol:
![20190814000337_1](https://user-images.githubusercontent.com/14364400/62982156-9db0ed80-be2b-11e9-864c-083d15b873fc.jpg)
You should be careful. The H&M debug panel (available in debug under your ACE self interaction) indicate 239 units, it is too much... 

Good luck!

**Comment by GoldJohnKing** [comment]
> Here is an example (I took your branch MPRI-Lythium):
MPRI-Lythium is a legacy branch now, we use MPRI-Lythium-TCL instead, but it's ok, though.

> First, a lot of them are ridiculously small and completely irrelevant accordingly to the type of city.

Would there be a method to force overwrite the city radius? As Lythium‘s city is pretty "flat", I bet it would be okay to do that. Or would it be better to change AI clear range to city activate radius but trigger AI clear at a much further distance, in order to suit situations like this?

> The old castle has a city radius correct

The old castle is a custom location added by myself in define_mod.sqf... 😅 
`[getMarkerPos "custom_loc_3","NameVillage","Old Castle",300,300,true],`
So the two "300" numbers means the city radius (a & b of a eclipse), which intends to AI spawn / despawn radius, instead of city activate range?

> When I tested your branch, I notice that some crazy AI number inside patrol:
I've noticed that there's two possibly related parameters in param.hpp, btc_p_mil_group_ratio and btc_p_patrol_max. I'd like to know which one controls the member counts in a partol group and which one controls partol group counts. If it's not related to above two parameters, please tell me where to find it.

Regards.

**Comment by Vdauphin** [comment]
> Would there be a method to force overwrite the city radius?

Yes, we could check if the city radius is very small and overwrite the city radius by something like 300m:
Add here [init.sqf#L57](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/init.sqf#L57) :
```
if (_radius_x < 100 || _radius_y < 100) then {
    _radius_x = 300;
    _radius_y = 300;
};
```
I didn't test the code but you have the idea or how it fit in Lythium. Try it in your computer with debug. You can clic on the map to move you quickly to location and watch the result.

>  Or would it be better to change AI clear range to city activate radius but trigger AI clear at a much further distance, in order to suit situations like this?

No because if the city radius is too small, all enemy will stack on each other and it will not looks great/realistic

> The old castle is a custom location added by myself in define_mod.sqf... 😅

You have a better idea how to configure this than the map authors ...

> So the two "300" numbers means the city radius (a & b of a eclipse), which intends to AI spawn / despawn radius, instead of city activate range?

300 meters means: Spawn AI under a circle of 300 meters and despawn AI under that same circle ([activate.sqf#L56](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L56))
spawn city radius offset parameter, you choosed 700m, means: if any player around a city in a radius of : 300 + 300 + 700 = 1300m then spawn AI in a circle of 300 meters ([trigger_player_side.sqf#L42](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf#L42))

btc_p_mil_group_ratio increase the AI density inside city, it doesn't chang the number of AI inside patrol. I think there were two patrols at the same position, so it is okay
btc_p_patrol_max increase the number of patrol, may be reduce it a little

**Comment by GoldJohnKing** [comment]
> Yes, we could check if the city radius is very small and overwrite the city radius by something like 300m:

Yep, I'll give a try.

> No because if the city radius is too small, all enemy will stack on each other and it will not looks great/realistic

You might have misunderstandings. I means "city active radius" instead of "AI spawn radius". For example, a city radius (which is also AI spawn radius) is 100m, but active radius 300m (players within 300m will cause city spawn AIs), and when player leaves 2*300=600m of the city, AIs in active radius (300m) will be despawned. It's just an example.

> 300 meters means: Spawn AI under a circle of 300 meters and despawn AI under that same circle (activate.sqf#L56)
spawn city radius offset parameter, you choosed 700m, means: if any player around a city in a radius of : 300 + 300 + 700 = 1300m then spawn AI in a circle of 300 meters (trigger_player_side.sqf#L42)

So the first 300 means AI spawning radius, while the second one means AI despawn radius?

> btc_p_mil_group_ratio increase the AI density inside city, it doesn't chang the number of AI inside patrol. I think there were two patrols at the same position, so it is okay
btc_p_patrol_max increase the number of patrol, may be reduce it a little

I'm just wondering if there's a method of generating more groups with less infantries instead of less groups with more infantries.

**Comment by Vdauphin** [comment]
I added the code calculating the radius for each fnc used during the process

[activate.sqf#L56](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L56), 
```sqf
private _radius_x = _city getVariable ["RadiusX", 0];
private _radius_y = _city getVariable ["RadiusY", 0];
private _radius = (_radius_x + _radius_y)/2;
```
So the fnc will create enemies in this `_radius`
If the radius city from config is 300m, the `_radius = 300`

[trigger_player_side.sqf#L42](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf#L42)
```sqf
_radius_x + _radius_y + btc_city_radius
```
This fnc activating city by calling [activate.sqf](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf) when player is inside a circle of `_radius_x + _radius_y + btc_city_radius`. `btc_city_radius` is the `btc_p_city_radius` you configured here : [param.hpp#L314-L318](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/def/param.hpp#L314-L318)
So if the radius city from config is 300m and the `btc_p_city_radius` is set to 700m, `300 + 300 + 700 = 1300`

[de_activate.sqf#L45](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf#L45)
```sqf
private _radius_x = _city getVariable ["RadiusX", 0];
private _radius_y = _city getVariable ["RadiusY", 0];
private _radius = _radius_x + _radius_y;
```
When player left the area (`_radius_x + _radius_y + btc_city_radius`), the function [de_activate.sqf](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf) remove all units in a circle of `_radius`.
So if the radius city from config is 300m, the `_radius` is `300 + 300  = 600`

Sorry for the lack of clarity and I hope I am not saying anything wrong :/

> I'm just wondering if there's a method of generating more groups with less infantries instead of less groups with more infantries.

This is what btc_p_mil_group_ratio does ([`_p_mil_group_ratio * (1 + random _max_number_group)`](https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf#L118))

**Comment by GoldJohnKing** [comment]
I get your point.

I've set: 
```
if (_radius_x < 300 || _radius_y < 500) then {
    _radius_x = 300;
    _radius_y = 500;
};
```
and city active range to 0m to see the city radius, this time it seems better than default.
![107410_20190814180234_1](https://user-images.githubusercontent.com/26923626/63013796-a9e68a80-bebf-11e9-80df-b05a1f9033a8.png)
![107410_20190814180250_1](https://user-images.githubusercontent.com/26923626/63013830-be2a8780-bebf-11e9-844e-6be3ab2e53cb.png)

I suggest adding above code to master branch and adding a parameter in param.hpp to control this, which might be called "Minimum radius of a city".

**Comment by Vdauphin** [comment]
Yes this looks way better

>I suggest adding above code to master branch and adding a parameter in param.hpp to control this,

This looks more like a requirements, I will look the exact number set in lythium and do a PR to fix it

**Comment by Vdauphin** [comment]
Take a little look to the PR.
Now even with small radius, the deactivation work as intended.
But I keep a minimum value because Lythium has some radius lower than 50m which can create issue. I tested with 80m, and it works fine
