### ISSUE TITLE
How does chemical propagate actually functions?

### ISSUE THREAD

**Issue by GoldJohnKing** [Vdauphin/HeartsAndMinds#815]
I'm modifying the original mission and aims to have certain ratio of civ and mil units spawned contaminated, in order to bring the virus spreading in China recently into the game.

I've tried my best to understand how it works and tried several ways of implementation but still failed. My modification always makes all spawned units contaminated. I could come up with no other idea except seeking for your help.

The most reliable one of my implementation is to add the code to "btc_fnc_civ_unit_create" and "btc_fnc_mil_unit_create", see: https://github.com/GoldJohnKing/HeartsAndMinds/commit/dc2bdf0b9d64ec81df77920f4b2c58680fa44f58

Though the equipment change code and virus propagation functions normally, all units are contaminated as they spawned no matter how I decrease the possibility. Could you please enlighten me what I did wrong and what else should I do?

**I've also found some potential bugs during the process.**

1. Units would yell "ouch" every time (within 3 seconds) when damage is applied, it's distracting and kind of funny. Though it might be better to remove the "ouch", I wonder if it could be realized due to ACE limitation.

2. When the amount of contaminated objects increases, every time checkLoop or damageLoop is executed, the graphics would stuck for few seconds. I start to notice the stuck at 10 objects contaminated and it becomes quite obvious at 16-20, above 20 would seriously impact gameplay. I've turned off ACE medical blood so it may not be an rendering issue. I tend to believe it's because EachFrame codes and EventHandler on units are unscheduled rather than scheduled. See: https://community.bistudio.com/wiki/Scheduler I still wonder if it's possible to improve due to engine limitation.

Another problem is sometimes player died within the propagate range keeps contaminated after respawned. But I'm not sure if it's caused by my former mentioned modification.

Thanks for your patience.

**Comment by Vdauphin** [comment]
Hello,

> How does chemical propagate actually functions?

Yes

> Could you please enlighten me what I did wrong and what else should I do?
```sqf
 //Edited: Add propagate possiblity to civ units
    if ((random 1) < 0.075 && ((btc_chem_contaminated pushBackUnique _x) > -1)) then {
        publicVariable "btc_chem_contaminated";
    };
```
The `(btc_chem_contaminated pushBackUnique _x) > -1` is always executed even when `(random 1) < 0.075` is `true`
use `{}` like that:
```sqf
 //Edited: Add propagate possiblity to civ units
    if ((random 1) < 0.075 && {(btc_chem_contaminated pushBackUnique _x) > -1}) then {
        publicVariable "btc_chem_contaminated";
    };
```
But honestly you should prefer use a second `if`, your code will do exactly what you want and it is more readable (it is also a very little faster in the case where `(random 1) < 0.075` is `false` ).

> Units would yell "ouch" every time (within 3 seconds) when damage is applied, it's distracting and kind of funny. Though it might be better to remove the "ouch", I wonder if it could be realized due to ACE limitation.

I don't know, you could ask to the ACE Team on ACE Slack.

> When the amount of contaminated objects increases, every time checkLoop or damageLoop is executed, the graphics would stuck for few seconds. I start to notice the stuck at 10 objects contaminated and it becomes quite obvious at 16-20, above 20 would seriously impact gameplay. I've turned off ACE medical blood so it may not be an rendering issue.

I have no idea, I will test. You could try to use https://forums.bohemia.net/forums/topic/211626-arma-script-profiler/ and look at the function freezing the game.

> I tend to believe it's because EachFrame codes and EventHandler on units are unscheduled rather than scheduled. See: https://community.bistudio.com/wiki/Scheduler I still wonder if it's possible to improve due to engine limitation.

Here is the explanation why unscheduled is better https://ace3mod.com/wiki/development/arma-3-scheduler-and-our-practices.html
In this case we need to find the script handling the game and change the code in H&M, CBA or ACE to avoid the issue.


> Another problem is sometimes player died within the propagate range keeps contaminated after respawned. But I'm not sure if it's caused by my former mentioned modification.

This should not happen because of this: 
https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/chem/damageLoop.sqf#L34-L36
and then this:
https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/chem/damageLoop.sqf#L44-L51
In debug mode you should see a message in chat and RPT saying  `btc_fnc_chem_damageLoop` `Stop`
I will also take a look as CBA has been updated

Good luck

**Comment by GoldJohnKing** [comment]
Thanks a lot! It now functions normally!

> > When the amount of contaminated objects increases, every time checkLoop or damageLoop is executed, the graphics would stuck for few seconds. I start to notice the stuck at 10 objects contaminated and it becomes quite obvious at 16-20, above 20 would seriously impact gameplay. I've turned off ACE medical blood so it may not be an rendering issue.
> 
> I have no idea, I will test. You could try to use https://forums.bohemia.net/forums/topic/211626-arma-script-profiler/ and look at the function freezing the game.

The ASP gives following result:
![屏幕截图(164)](https://user-images.githubusercontent.com/26923626/74240363-c7809980-4d14-11ea-95df-275b09f29193.png)
![屏幕截图(165)](https://user-images.githubusercontent.com/26923626/74240624-57bede80-4d15-11ea-9236-ee274154f3b8.png)
![屏幕截图(166)](https://user-images.githubusercontent.com/26923626/74241042-272b7480-4d16-11ea-8d93-7ac8927d757f.png)

I dont know why my ASP just cant save tracy files on my computer... The file just doesnt appear, so there's only screenshots.

**Comment by Vdauphin** [comment]
Thanks for arma script profiler screen I will take a deeped look. I mostly design this for player. So the damage.sqf is apply client side (if the player is contaminated) so it is fine. But for AI, it is handle by the server, so I need to delay the damage.sqf for each AI so you dont have 20 damage.sqf executed in the same time.

> I've tried several times, it seems that player died of bleeding out (or in coma) would keep contaminated. In this circumstances, the log seems not popping.

You need to know that dead body stay contaminated, I will look at it

>  Or the GetIn event handler would also trigger as well as unit is spawned into the vehicle?

No, mainly because the EH is added after unit creation ^^.

> Do I need the following code in order to contaminate the whole vehicle of units spawned contaminated?
> { btc_chem_contaminated pushBackUnique _x; } forEach fullCrew vehicle _x; 

This is not necessary as the `btc_fnc_chem_checkLoop` will propagate to other crew because they are close enough.

> `btc_chem_contaminated pushBackUnique vehicle _x;`

I will add this line where vehicle are initialized for consistency (like in https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf).

**Comment by Vdauphin** [comment]
> Another problem is sometimes player died within the propagate range keeps contaminated after respawned. But I'm not sure if it's caused by my former mentioned modification.

![20200211190714_1](https://user-images.githubusercontent.com/14364400/74265022-022d0680-4d02-11ea-99ab-cc6bad73ddc6.jpg)
Working as intended

**Comment by Vdauphin** [comment]
If approuved, this https://github.com/acemod/ACE3/pull/7521 could help reducing lag
Also I am testing this https://github.com/Vdauphin/HeartsAndMinds/pull/816

**Comment by GoldJohnKing** [comment]
> This is not necessary as the btc_fnc_chem_checkLoop will propagate to other crew because they are close enough.

The checkLoop propagates both crews and vehicle, or just crews?

**Comment by Vdauphin** [comment]
> The checkLoop propagates both crews and vehicle, or just crews?

CheckLoop do this:
https://github.com/Vdauphin/HeartsAndMinds/blob/master/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/chem/checkLoop.sqf#L72-L77

This mean if a unit is in a range of an unit or object contaminated then contaminate it.
So if a contaminated unit is inside a vehicle, the crew next to him will be contaminated and also unit outside the vehicle if there are in range.
Vehicle could only be contaminated if a contaminated unit get in the vehicle.

**Comment by GoldJohnKing** [comment]
I got your point. Your replies do help a lot. 👍
