### ISSUE TITLE
Adding More Headless Clients

### ISSUE THREAD

**Issue by SgtKrunch** [Vdauphin/HeartsAndMinds#955]
As the title suggests, is it possible to add multiple headless clients to be used and supported in H&M? What would I need to change other than adding the headless clients to the mission? Like, would it be possible to use 1 HC for civilian patrols, another HC for military patrols, then one or two more for the groups that spawn on the map?

**Comment by Vdauphin** [comment]
Hello,
>  is it possible to add multiple headless clients to be used and supported in H&M?

http://vdauphin.github.io/HeartsAndMinds/InGame-documentation#headless--database

> What would I need to change other than adding the headless clients to the mission?

You need to detect when a other Headless come and migrate AI you want to this new headless

> Like, would it be possible to use 1 HC for civilian patrols, another HC for military patrols, 

The number of civilian patrols is so low that one headless just for them is really useless

> then one or two more for the groups that spawn on the map?

H&M spawn AI when player enter in city and remove them when player leave. So it is not necessary to add headless for them. This will also add desync to player because AI need to be transfer to headless every time a new city is activate or deactivated

**Comment by SgtKrunch** [comment]
In your opinion then, would it be worth it to add more headless clients? I thought it would be a good idea to be able to utilize the resources we have on our server, but it sounds like it might not be worth it.

**Comment by Vdauphin** [comment]
The real question is, what is your server FPS during playing without headless
If the server FPS is too low you will see strange AI behavior, like they are not moving.

Then you should consider to use a headless. But you should not use the headless for AI in city because if you travel across the map those AI will be remove dynamically. This will generate network traffic between server and headless. And as we know, arma is really bad in network
That why in H&M, headless is only use to civilian traffic and enemies patrol because those AI are "persistent" and are just remove when they reach their destination.

The best dedicate should have one core (because Arma use one core) with a really high frequency.

**Comment by GoldJohnKing** [comment]
I'm so confused, does H&M's auto headless client feature already support more than 1 HC?

(That link is 404.)

**Comment by Vdauphin** [comment]
This mission automatically uses one Headless client when available.
Only one.

**Comment by GoldJohnKing** [comment]
Ah... I get that.

My players want a more immersive experience by populating lots more civilians and animals and enemy patrols, so I probably need up to 3 HCs.

I've look through the code and find this:

https://github.com/Vdauphin/HeartsAndMinds/blob/d0baf935c7eaa5a6e6c3d84be1859e5967f469cc/%3DBTC%3Dco%4030_Hearts_and_Minds.Altis/core/fnc/common/set_groupsowner.sqf#L32

so would it be useful to make H&M support multiple HCs if I just change this line into:

`private _HC = owner (selectRandom _HCs);`

**Comment by Vdauphin** [comment]
> My players want a more immersive experience by populating lots more civilians and animals and enemy patrols

Animals are just agents
more civilians are not migrate to HC, only civilian traffic

> I probably need up to 3 HCs.

Just check your `#monitor`, pretty sure it is already okay. Before increasing the number of Headless, you should check if your server FPS is low and your CPU is not at 100%. Desync and temporary lag will not be resolve by headless. Most of those issue is due to hard drive from client in `master_daily` branch.

> I've look through the code and find this:

H&M only handle HC for civilian traffic and enemies patrol so increase the number of HC will only dilute civilian traffic and enemies patrol.

**Comment by GoldJohnKing** [comment]
Thanks a lot! You explain it really clear, I totally get it.
